---
title: "20200918_Pathak_Vinayak_HW2"
author: Your Name
date: 2020-09-12
output: html_document
---

# BME 590 Homework 2

---

*In this homework, the objectives are to*

1. Work with dates in R and exploratory data visualization

2. Data Preprocessing and Transformation

Assignments will only be accepted in electronic format in RMarkdown (.rmd) files and knitted .html files. Your code should be adequately commented to clearly explain the steps you used to produce the analyses. RMarkdown homework files should be uploaded to Sakai with the naming convention date_lastname_firstname_HW[X].Rmd. For example, my first homework assignment would be named 20200911_Dunn_Jessilyn_HW1.Rmd. **It is important to note that 5 points will be deducted for every assignment that is named improperly.** Please add your answer to each question directly after the question prompt in  the homework .Rmd file template provided below.

---

## Datasets

1. Heart Disease 
https://archive.ics.uci.edu/ml/datasets/Heart+Disease

2. Coronavirus
https://ourworldindata.org/coronavirus-source-data

You have seen both datasets in the HW1. Please refer to these pages for additional information. Note that the coronavirus dataset is a newer version compared to the one we used in the HW1, so please use the newer version in this HW.

```{r message=FALSE}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(patchwork)
library(gridExtra)
```

---

## Working with Dates and EDA

1. Unzip the file "owid-covid-data.csv.gz" (downloadable from sakai HW2 assignment page) using whichever method you prefer (one option we suggest is the “unzip” or the “gunzip” command in bash) and load this dataset into this R Markdown file using **read.csv()**. Select the following features from the original data file and save just these fields into a  dataframe named *covid_df*: 

iso_code
continent 
location 
date
population
total_cases
new_cases 
total_deaths
new_deaths
total_cases_per_million
new_cases_per_million
total_deaths_per_million
new_deaths_per_million 
positive_rate

(5 points)
```{bash}
gunzip owid-covid-data.csv.gz
```

2. The **date** column in *covid_df* was automatically designated by R as a factor (which is a categorical variable designation) or a string (which is a character variable designation) and is therefore not understandable in R as a datetime object in its current form. Use the package **lubridate** to create a new vector named **Date** that contains the transformed **date** column structured as a POSIXct date-time object. Replace the  **date** column in the existing dataframe *covid_df* with the updated POSIXct date-time formatted **Date** column that you’ve just created(5 points)

3. Use **ggplot2** to create a grid of marker+line plots containing 3 subplots in a 3 by 1 grid (3 rows by 1 column) to show the change in COVID-19 infection over time for the USA. The order of the three plots from the top to bottom of the grid should be  *new_cases_per_million*, *new_deaths_per_million* and *positivite_rate*. Clearly label your y-axes and x-axes with the names of the variables and their units. (You can refer to the codebook from last HW for details.) I recommend using the package "patchwork" for making multiple plots, but you can also use other packages for this purpose. (10 points)

4. What are the trends you observe for these three different measures? E.g. When do the highest values occur for each metric? Are these metrics decreasing or increasing at the latest recorded date? Clearly explain your answer for full mark. You can also comment on how these observations correspond with public health efforts (e.g. mask-wearing, physical distancing, and stay-at-home orders) . (5 points)

---

## Exploratory Data Analysis and Data Preprocessing

1. From the same heart disease dataset in the file "heart_disease_df.csv", create a new dataframe named "heart_df" that contains information on the subjects' age, sex, resting blood pressure (trestbps), serum cholesterol level (chol), maximum heart rate (thalach), ST depression induced by exercise relative to rest (oldpeak) as well as the new column "diagnosed" in TRUE/FALSE. This is the dataset you worked with in the last HW, and information of this dataset (including all column names) is available at the website: https://archive.ics.uci.edu/ml/datasets/Heart+Disease. (6 points)

2. Cast all columns into the most sensible variable type, e.g., "age" should be an integer, "sex" should be a factor, and "diagnosed" should be a logical. (4 points)

3. Using ggplot and the grid drawing method of your choice, draw a 2-by-2 grid of 4 density histograms with the density curves overlaid on the same plot. Do this for **resting blood pressure**, **serum cholesterol level**, **maximum heart rate** and **ST depression induced by exercise relative to rest**.I recommend using the library "patchwork" or “gridExtra” for making the 4-plot grid. Label your axes and legend appropriately for full credit. You should also choose a suitable histogram bin width for each variable and explain why you made that choice. (10 points)

4. Now using a similar 2 by 2 grid, overlay two separate density curves for the diseased and healthy groups, for each variable (feature) from question 3.  For these figures, plot the just the density curve(without the density histogram bins). Add a vertical line for each of the two density curves on each plot at the mean value for that combined feature and diagnosis group. For example, in the first grid, which is row 1 and column 1 of the 2-by-2 grid, there should be two density plots drawn in two colors for the two different diagnosis groups (diagnosed = TRUE and diagnosed = FALSE). (20 points)

5. What are your observations? E.g. Does any feature visually show a strong difference in means or in shape of the data between the two diagnosis groups? For each feature, which diagnosis group seems to have a higher average value? Clearly explain your answer to receive full mark. (5 points)

6. By observing the histogram and density plots of all four predictors, answer the following questions for each of the predictors/variables:
a. Is the dataset for each predictor/variable skewed?
b. Does it have positive skewness or negative skewness? (Think about to question 5 in the section above.)
c. Compute the skewness using the definition from the lecture.
d. According to the criterion introduced in the lecture, is the dataset moderately skewed or highly skewed?
(10 points)

7. Correlation plots are a way to visualize multivariate relationships. Using the corrplot package, make a correlation plot of the fields in the dataframe **heart_df**. Clearly label your axis and legend for full marks. Which factor has the strongest correlation with the diagnosis status? (10 points)

9. Perform winsorization on the **serum cholesterol level** dataset. Typically, you can decide a threshold (typically a specific range of percentiles) and replace all the data points outside of the threshold with the closest value from within the threshold. An example from Wikipedia may be a helpful demonstration: “a 90% winsorization would see all data below the 5th percentile set to the 5th percentile, and data above the 95th percentile set to the 95th percentile.” Conduct a 90% winsorization on the cholesterol level dataset and plot a histogram of the winsorized data. What is your observation? (5 points)

10. Another method to normalize highly skewed data is to use log-scale transformation. Perform log-scale transformation on **ST depression induced by exercise relative to rest** dataset by adding 1 to each observation and taking a natural log. Plot the log-transformed histogram. What is your observation? (5 points)

